2023-12-05 14:02:27,853 INFO    ThreadPoolExecutor-0_2:60899 [wandb_init.py:init():547] calling init triggers
2023-12-05 14:02:27,854 INFO    ThreadPoolExecutor-0_0:60899 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-12-05 14:02:27,880 INFO    ThreadPoolExecutor-0_2:60899 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'S': 4, 'beta': 1.0, 'batch_size': 32, 'num_iters': 50000, 'lr': 0.001, 'lr_decay': 0.9, 'lr_decay_every': 1000, 'experiment-name': 'decoders'}
2023-12-05 14:02:27,881 INFO    ThreadPoolExecutor-0_3:60899 [wandb_init.py:init():703] updated telemetry
2023-12-05 14:02:27,881 INFO    ThreadPoolExecutor-0_0:60899 [wandb_setup.py:_flush():76] Configure stats pid to 60899
2023-12-05 14:02:27,881 INFO    ThreadPoolExecutor-0_2:60899 [wandb_init.py:init():596] starting backend
2023-12-05 14:02:27,882 INFO    ThreadPoolExecutor-0_0:60899 [wandb_setup.py:_flush():76] Loading settings from /Users/sach/.config/wandb/settings
2023-12-05 14:02:27,882 INFO    ThreadPoolExecutor-0_2:60899 [wandb_init.py:init():600] setting up manager
2023-12-05 14:02:27,882 INFO    ThreadPoolExecutor-0_0:60899 [wandb_setup.py:_flush():76] Loading settings from /Users/sach/Development/Python/VANO/wandb/settings
2023-12-05 14:02:27,882 INFO    ThreadPoolExecutor-0_0:60899 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-05 14:02:27,883 INFO    ThreadPoolExecutor-0_0:60899 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-05 14:02:27,883 INFO    ThreadPoolExecutor-0_0:60899 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'experiments/2d_gaussian_pdf.py', 'program': '/Users/sach/Development/Python/VANO/experiments/2d_gaussian_pdf.py'}
2023-12-05 14:02:27,883 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:_log_setup():507] Logging user logs to /Users/sach/Development/Python/VANO/wandb/run-20231205_140227-fkhtlhkv/logs/debug.log
2023-12-05 14:02:27,884 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/sach/Development/Python/VANO/wandb/run-20231205_140227-fkhtlhkv/logs/debug-internal.log
2023-12-05 14:02:27,884 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:init():547] calling init triggers
2023-12-05 14:02:27,884 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'S': 4, 'beta': 1.0, 'batch_size': 32, 'num_iters': 50000, 'lr': 0.001, 'lr_decay': 0.9, 'lr_decay_every': 1000, 'experiment-name': 'decoders'}
2023-12-05 14:02:27,884 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:init():596] starting backend
2023-12-05 14:02:27,884 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:init():600] setting up manager
2023-12-05 14:02:27,891 INFO    ThreadPoolExecutor-0_2:60899 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-12-05 14:02:27,905 INFO    ThreadPoolExecutor-0_0:60899 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-12-05 14:02:27,906 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:init():606] backend started and connected
2023-12-05 14:02:27,909 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:init():703] updated telemetry
2023-12-05 14:02:27,909 INFO    ThreadPoolExecutor-0_2:60899 [wandb_init.py:init():606] backend started and connected
2023-12-05 14:02:27,910 INFO    ThreadPoolExecutor-0_2:60899 [wandb_init.py:init():703] updated telemetry
2023-12-05 14:02:27,922 INFO    ThreadPoolExecutor-0_3:60899 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-12-05 14:02:27,928 INFO    ThreadPoolExecutor-0_0:60899 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-12-05 14:02:27,930 INFO    ThreadPoolExecutor-0_2:60899 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-12-05 14:02:28,312 WARNING MsgRouterThr:60899 [router.py:message_loop():77] message_loop has been closed
